### ISSUE TITLE
may be a module name before err code is needed

### ISSUE THREAD

**Issue by yangjuncode** [vsrc/isecode#1]
when multiple lib being imported, it will be conflict when no moudle name as prefix.

"ERROR 7248152: Something went wrong, please contact us."
vs
"ERROR modulename-7248152: Something went wrong, please contact us."

of course, modulename default to empty when in small program.

**Comment by pycckuu** [comment]
Or maybe just add possibility to prepend some custom letters in front of the error code, e.g. MA526263, will be sufficient?

**Comment by vsrc** [comment]
I like the idea! I will add the option to pass the prefix. Thanks both @yangjuncode and @pycckuu for the suggestion!

**Comment by vsrc** [comment]
Just updated the code in the v1.0.1. Thanks again both!
